### PR TITLE
Add links to CHiPs44 repositories

### PR DESCRIPTION
**Pull request by tuupola**

### CODE REVIEW

**Comment by tuupola** [comment]
@CHiPs44 are these ok with you?

**Comment by CHiPs44** [comment]
I need to add a big fat warning about the fact neither project is production ready, but yes, that's OK!

**Comment by tuupola** [comment]
Well HAGL is not production ready either :) Hopefully can tag 1.0.0 in near future.

**Comment by CHiPs44** [comment]
I'm preparing a PR for styled char/text, but #94 should be merged first.

**Pull request merged**
