### PR TITLE
Add surface and backend concepts

### PR DESCRIPTION
**Pull request by tuupola**

### CODE REVIEW

**Comment by tuupola** [comment]
Notes:

https://gist.github.com/rianhunter/0be8dc116b120ad5fdd4
https://cseweb.ucsd.edu/~calder/papers/POPL-94.pdf
https://hbfs.wordpress.com/2008/12/30/the-true-cost-of-calls/

**Comment by UncleRus** [comment]
I'm a little confused on the concept, correct me:
- Backend - it's clear what it is. It is needed to provide low-level functions that interact directly with the device. Allows you to have multiple physical devices in one project.
- Bitmap - also clear. We can draw on it, we can use it as sprites, etc.
- The surface - but here it is already incomprehensible. What functionality does it carry? Allows you to use multiple physical devices as one screen?

**Comment by UncleRus** [comment]
And I also want to say that I really like the way in which hagl develops.

**Comment by UncleRus** [comment]
How about this option (sorry if it sounds stupid): the backend always provides a single bitmap. In this case, the surface becomes unnecessary - we can draw both on the backend bitmap and on the created one.
The disadvantage is obvious - this may lead to additional buffering, which can be harmful on large full-color displays (bitmaps of their backends will take up a lot of RAM).
However, this minus can be dealt with by merging the logic of bitmap and the surface - you can provide a flag inside the bitmap structure that will determine whether this bitmap is "real" or just a proxy to the backend.

**Comment by UncleRus** [comment]
And I would like one more thing: right now I have a project in which I would really like to use hagl, but I can’t, because this project uses two different displays at the same time (sd1306 and sd1322), while it also assumes the possibility of changing their connection (selection of GPIO) at runtime. I think the backend concept is a great step in that direction.

**Pull request merged**
