### PR TITLE
Remove DISPLAY_[WIDTH|HEIGHT|DEPTH] & HAGL_CHAR_BUFFER_SIZE macros

### PR DESCRIPTION
**Pull request by CHiPs44**
I didn't test the JPEG modification, but it's pretty straightforward.

### CODE REVIEW

**Comment by CHiPs44** [comment]
Please don't merge at the moment, there are a few bugs left.

**Comment by CHiPs44** [comment]
- Styled char/text experiment: background/foreground colors and normal/reverse, transparency needs better blit functions 
- Unified void *_surface across API

**Comment by CHiPs44** [comment]
Sorry for the mess, PR should be titled "Remove DISPLAY_ macros, styled text proposal and _surface param", now...

**Comment by tuupola** [comment]
Now there is too many things in one PR. Could you keep them separate? PR should have only either one fix or new feature. Removing internal usage of `DISPLAY_WIDTH` was also in my TODO list and it already looked good.

**Comment by CHiPs44** [comment]
Closing this one, I'll make several one thing at a Time ASAP.

**Pull request closed without merging**
